var_groups: [gridmet, pm25_ushap, aqdh, census, climate_types]
min_year: 2000
max_year: 2010
data_dir: data/output/
summary_stats_dir: summary_statistics
sumnmary_stats_nm: summary_statistics
normalize: false
verbose: true


hydra:
  run:
    dir: logs/dataloader/${now:%Y-%m-%d}/${now:%H-%M-%S}